version: 2
build:
  os: ubuntu-22.04
  tools: { python: "3.11" }
  apt_packages:
  - doxygen
  jobs:
    pre_build:
      - cd docs && mkdir -p _build/doxygen && doxygen Doxyfile
sphinx:
  configuration: docs/conf.py
python:
  install:
    - requirements: docs/requirements.txt

# Optional: build extra formats
formats:
  - htmlzip
  - pdf
  - epub