version: 2
build:
  os: ubuntu-22.04
  tools: { python: "3.11" }
  apt_packages:
    - doxygen
  jobs:
    pre_build:
      - mkdir -p docs/_build/doxygen && doxygen docs/Doxyfile
sphinx:
  configuration: docs/conf.py

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - dev
formats:
  - htmlzip
